name: sp500_app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - plotly
  - scikit-learn
  - statsmodels
  - matplotlib
  - pyarrow
  - seaborn
  - pytz
  - pip:
    - altair==5.5.0
    - attrs==25.3.0
    - blinker==1.9.0
    - cachetools==5.5.2
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - click==8.1.8
    - cmdstanpy==1.2.5
    - colorama==0.4.6
    - contourpy==1.3.2
    - cycler==0.12.1
    - fonttools==4.57.0
    - gitdb==4.0.12
    - GitPython==3.1.44
    - holidays==0.71
    - idna==3.10
    - importlib_resources==6.5.2
    - Jinja2==3.1.6
    - joblib==1.5.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2025.4.1
    - kiwisolver==1.4.8
    - MarkupSafe==3.0.2
    - narwhals==1.37.1
    - packaging==24.2
    - patsy==1.0.1
    - pillow==11.2.1
    - prophet==1.1.6
    - protobuf==6.30.2
    - pydeck==0.9.1
    - pyparsing==3.2.3
    - python-dateutil==2.9.0.post0
    - referencing==0.36.2
    - requests==2.32.3
    - rpds-py==0.24.0
    - scipy==1.15.2
    - six==1.17.0
    - smmap==5.0.2
    - stanio==0.5.1
    - tenacity==9.1.2
    - threadpoolctl==3.6.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - typing_extensions==4.13.2
    - tzdata==2025.2
    - urllib3==2.4.0
    - watchdog==6.0.0
